-- my_sls_export.lua
-- SLS (Selective Laser Sintering) 自定义导出脚本
--
-- 该脚本实现SLS切片数据的自定义导出，包括：
--   1. 将层轮廓多边形和配置信息打包为zip文件
--   2. 注册数据库记录（SQLite/MySQL/PostgreSQL）
--
-- Lua 环境全局变量:
--   config      : table { path="config.json", configStr="<JSON content>" }
--   images      : array, 每个元素为 { path="layers/N.json", data="<polygon JSON>" }
--   output_path : string, 输出文件路径（由C++传入）
--
-- 可用的已注册Lua库:
--   Zipper          : zip压缩包操作（add_file, save）
--   Cipher          : 加密/哈希
--   Bit7zZipper     : 7z压缩（可选）
--   SQLiteAdapter   : SQLite数据库操作
--   MySQLAdapter    : MySQL数据库操作（如果编译时启用）
--   PostgreSQLAdapter : PostgreSQL数据库操作（如果编译时启用）
--
-- 返回值: table { success = true/false, export_path = "..." }

function export_sls()
    -- 1. 创建zip压缩包
    local zipper = Zipper.new()

    -- 2. 写入配置文件
    zipper:add_file(config.path, config.configStr)

    -- 3. 写入每层的多边形轮廓数据
    for i, img in ipairs(images) do
        zipper:add_file(img.path, img.data)
    end

    -- 4. 写入README说明
    local readme = "SLS Export Package\n"
    readme = readme .. "==================\n"
    readme = readme .. "Generated by HsBaSlicer SLS Pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: Slicing and laser configuration\n"
    readme = readme .. "  - layers/: Per-layer polygon outlines (JSON format)\n\n"
    readme = readme .. "Layer JSON format:\n"
    readme = readme .. '  { "layer": N, "z_height": Z, "outlines": { "polygons": [...] } }\n'
    zipper:add_file("README.txt", readme)

    -- 5. 保存zip文件
    local out_path = output_path or "sls_output.zip"
    zipper:save(out_path)

    -- 6. 注册数据库记录（可选 - 使用SQLite示例）
    local db_ok, db_err = pcall(function()
        local db = SQLiteAdapter.open("sls_history.db")
        db:execute([[
            CREATE TABLE IF NOT EXISTS sls_exports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                output_path TEXT NOT NULL,
                total_layers INTEGER,
                export_time TEXT DEFAULT (datetime('now'))
            )
        ]])
        db:execute(string.format(
            "INSERT INTO sls_exports (output_path, total_layers) VALUES ('%s', %d)",
            out_path, #images
        ))
        db:close()
    end)

    if not db_ok then
        -- Database registration failure is non-fatal, just log it
        print("[SLS Export] Warning: database registration skipped: " .. tostring(db_err))
    end

    return {
        success = true,
        export_path = out_path
    }
end

return export_sls()
