#define BOOST_TEST_MODULE gcode_path_test
#include <boost/test/included/unit_test.hpp>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>

#include <lua.hpp>

#include "base/error.hpp"
#include "paths/gcodepath.hpp"

using namespace HsBa::Slicer;

namespace
{
GCodePrinterConfig MakeConfig()
{
    GCodePrinterConfig cfg;  // defaults: 0.4 nozzle, 1.75 filament, 200/60 deg, speeds 50/100/20
    return cfg;
}

// one closed triangle polygon as expected by LayersPath::push_back
PolygonsD SampleLayer()
{
    PolygonsD polys;
    polys.emplace_back();
    polys[0].push_back(Point2D{0.0, 0.0});
    polys[0].push_back(Point2D{10.0, 0.0});
    polys[0].push_back(Point2D{0.0, 10.0});
    return polys;
}

bool Contains(const std::string& haystack, std::string_view needle)
{
    return haystack.find(needle) != std::string::npos;
}
}  // namespace

BOOST_AUTO_TEST_SUITE(gcode_path_test)

BOOST_AUTO_TEST_CASE(header_footer_per_firmware)
{
    GCodePath path{MakeConfig()};

    auto marlin = path.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(Contains(marlin, "; Generated by HsBaSlicer"));
    BOOST_CHECK(Contains(marlin, "; Firmware: Marlin"));
    BOOST_CHECK(Contains(marlin, "M104 S200"));
    BOOST_CHECK(Contains(marlin, "M140 S60"));
    BOOST_CHECK(Contains(marlin, "G28 ; home all axes"));
    BOOST_CHECK(Contains(marlin, "M82 ; absolute extrusion"));
    BOOST_CHECK(Contains(marlin, "G1 Z5.0 F6000"));  // travel_speed 100 * 60
    BOOST_CHECK(Contains(marlin, "M84 ; disable motors"));
    BOOST_CHECK(!Contains(marlin, "M106"));             // fan command is RepRap only
    BOOST_CHECK(!Contains(marlin, "SET_PRESSURE_ADVANCE"));  // Klipper only

    auto reprap = path.ToGCode(GCodeFirmware::RepRap);
    BOOST_CHECK(Contains(reprap, "; Firmware: RepRap/RRF"));
    BOOST_CHECK(Contains(reprap, "M106 S255 ; fan on full"));
    BOOST_CHECK(Contains(reprap, "M107 ; fan off"));

    auto klipper = path.ToGCode(GCodeFirmware::Klipper);
    BOOST_CHECK(Contains(klipper, "; Firmware: Klipper"));
    BOOST_CHECK(Contains(klipper, "SET_PRESSURE_ADVANCE ADVANCE=0.05"));
    BOOST_CHECK(Contains(klipper, "SET_FAN_SPEED FAN=part_fan SPEED=1.0"));
    BOOST_CHECK(Contains(klipper, "SET_FAN_SPEED FAN=part_fan SPEED=0.0"));
    BOOST_CHECK(Contains(klipper, "M220 S100"));

    // footer retract command uses configured length/speed (1.0 mm @ 40 mm/s)
    BOOST_CHECK(Contains(marlin, "G1 E-1 F2400 ; retract"));

    // relative extrusion switches the mode command
    GCodePrinterConfig rel = MakeConfig();
    rel.relative_extrusion = true;
    GCodePath rel_path{rel};
    BOOST_CHECK(Contains(rel_path.ToGCode(GCodeFirmware::Marlin), "M83 ; relative extrusion"));

    BOOST_CHECK(rel_path.printerConfig().relative_extrusion);
    BOOST_CHECK(!path.printerConfig().relative_extrusion);
}

BOOST_AUTO_TEST_CASE(layer_generation_with_z_and_extrusion)
{
    GCodePath path{MakeConfig()};
    path.push_back("Z:0.20", SampleLayer());
    path.push_back("Z:0.40", SampleLayer());

    auto gcode = path.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(Contains(gcode, ";LAYER:0"));
    BOOST_CHECK(Contains(gcode, ";LAYER:1"));
    BOOST_CHECK(Contains(gcode, "G0 Z0.200"));
    BOOST_CHECK(Contains(gcode, "G0 Z0.400"));
    // first layer prints at first_layer_speed 20 mm/s, later layers at 50 mm/s
    BOOST_CHECK(Contains(gcode, "F1200"));
    BOOST_CHECK(Contains(gcode, "F3000"));
    // absolute extrusion accumulates: the last E of layer 1 must be larger than layer 0's
    BOOST_CHECK(Contains(gcode, "G1 X10.000 Y0.000 E"));

    // second polygon in the same layer triggers travel retraction/unretract
    PolygonsD two_polys = SampleLayer();
    two_polys.push_back(SampleLayer()[0]);
    GCodePath multi{MakeConfig()};
    multi.push_back("Z:0.20", two_polys);
    auto multi_gcode = multi.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(Contains(multi_gcode, "; retract"));
    BOOST_CHECK(Contains(multi_gcode, "; unretract"));

    // disabling retraction removes those moves
    GCodePrinterConfig no_ret = MakeConfig();
    no_ret.enable_retraction = false;
    GCodePath no_ret_path{no_ret};
    no_ret_path.push_back("Z:0.20", two_polys);
    BOOST_CHECK(!Contains(no_ret_path.ToGCode(GCodeFirmware::Marlin), "; unretract"));
}

BOOST_AUTO_TEST_CASE(layer_config_z_parsing_edge_cases)
{
    GCodePath path{MakeConfig()};
    PolygonsD empty_poly;  // no polygons at all
    path.push_back("plain_config", empty_poly);       // no Z: prefix -> z = 0
    path.push_back("Z:notanumber", empty_poly);       // invalid_argument -> z = 0
    path.push_back("Z:1e999999", empty_poly);         // out_of_range -> z = 0
    path.push_back("Z:", empty_poly);                 // tiny suffix -> z = 0

    auto gcode = path.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(Contains(gcode, "G0 Z0.000"));
    BOOST_CHECK(Contains(gcode, ";LAYER:3"));
}

BOOST_AUTO_TEST_CASE(continuous_wall_spiral_mode)
{
    GCodePath path{MakeConfig()};
    BOOST_CHECK(!path.hasContinuousWall());

    std::vector<PathPoint3D> wall;
    wall.push_back({0.0, 0.0, 0.0});
    wall.push_back({10.0, 0.0, 0.2});
    wall.push_back({10.0, 10.0, 0.4});
    path.setContinuousWall(wall);
    BOOST_CHECK(path.hasContinuousWall());

    auto gcode = path.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(Contains(gcode, "G0 X0.000 Y0.000 Z0.000"));
    BOOST_CHECK(Contains(gcode, "G1 X10.000 Y0.000 Z0.200 E"));
    BOOST_CHECK(Contains(gcode, "G1 X10.000 Y10.000 Z0.400 E"));
    // the helix must stay extrusion-continuous: no retraction between the wall
    // points themselves (the footer's end retract lies past the last wall move)
    const auto wall_start = gcode.find("G0 X0.000 Y0.000 Z0.000");
    const auto wall_end = gcode.find("G1 X10.000 Y10.000 Z0.400");
    BOOST_CHECK(wall_start != std::string::npos);
    BOOST_CHECK(wall_end != std::string::npos);
    auto wall_section = gcode.substr(wall_start, wall_end - wall_start);
    BOOST_CHECK(wall_section.find("; retract") == std::string::npos);

    // relative extrusion variant exercises the per-point E branch
    GCodePrinterConfig rel = MakeConfig();
    rel.relative_extrusion = true;
    GCodePath rel_path{rel};
    rel_path.setContinuousWall(wall);
    BOOST_CHECK(Contains(rel_path.ToGCode(GCodeFirmware::Marlin), "G1 X10.000 Y0.000 Z0.200 E"));

    // a wall with a single point emits nothing (size < 2 early return)
    GCodePath stub{MakeConfig()};
    stub.setContinuousWall({PathPoint3D{1.0, 1.0, 0.0}});
    auto stub_gcode = stub.ToGCode(GCodeFirmware::Marlin);
    BOOST_CHECK(!Contains(stub_gcode, "G1 X1.000 Y1.000 Z"));
}

BOOST_AUTO_TEST_CASE(save_gcode_writes_file_and_reports_errors)
{
    GCodePath path{MakeConfig()};
    path.push_back("Z:0.20", SampleLayer());

    auto tmp = std::filesystem::temp_directory_path() / "hsba_gcode_out.gcode";
    std::error_code ec;
    std::filesystem::remove(tmp, ec);
    path.SaveGCode(tmp, GCodeFirmware::Klipper);
    BOOST_CHECK(std::filesystem::exists(tmp));
    std::ifstream ifs(tmp, std::ios::binary);
    std::string content((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
    BOOST_CHECK(Contains(content, "; Firmware: Klipper"));
    std::filesystem::remove(tmp, ec);

    // an unwritable location (missing parent directory) must raise the project
    // RuntimeError; a non-existent sub-dir fails to open on both POSIX and Windows
    BOOST_CHECK_THROW(path.SaveGCode(std::filesystem::path("hsba_no_such_dir_xyz/out.gcode"), GCodeFirmware::Marlin),
                      HsBa::Slicer::RuntimeError);
}

BOOST_AUTO_TEST_CASE(lua_post_processing_variants)
{
    GCodePath path{MakeConfig()};
    path.push_back("Z:0.20", SampleLayer());
    const std::string base = path.ToGCode(GCodeFirmware::Marlin);

    // empty script short-circuits to the base output
    BOOST_CHECK_EQUAL(path.ToGCode(GCodeFirmware::RepRap, ""), path.ToGCode(GCodeFirmware::RepRap));

    // returned string replaces the output; globals are visible to the script
    auto appended = path.ToGCode(GCodeFirmware::Marlin, "return gcode .. ';CUSTOM\\n'");
    BOOST_CHECK(Contains(appended, ";CUSTOM"));
    BOOST_CHECK(Contains(appended, "; Generated by HsBaSlicer"));

    // firmware + printer_config globals are exported correctly
    auto fw = path.ToGCode(GCodeFirmware::Klipper, "return firmware .. '|' .. "
                                                  "tostring(printer_config.total_layers) .. '|' .. "
                                                  "string.format('%.0f', printer_config.nozzle_temp)");
    BOOST_CHECK_EQUAL(fw, "klipper|1|200");

    auto reprap_fw = path.ToGCode(GCodeFirmware::RepRap, "return firmware");
    BOOST_CHECK_EQUAL(reprap_fw, "reprap");

    // numbers are string-coercible in Lua, so a numeric return becomes text
    BOOST_CHECK_EQUAL(path.ToGCode(GCodeFirmware::Marlin, "return 42"), "42");

    // a non-coercible (table) return with no 'result' global falls back to base
    BOOST_CHECK_EQUAL(path.ToGCode(GCodeFirmware::Marlin, "return {}"), base);

    // 'result' global is honoured when nothing is returned
    auto via_global = path.ToGCode(GCodeFirmware::Marlin, "result = 'FROM_GLOBAL'");
    BOOST_CHECK_EQUAL(via_global, "FROM_GLOBAL");

    // lua_reg callback runs before the script and can expose extra globals
    auto with_reg = path.ToGCode(
        GCodeFirmware::Marlin, "return injected",
        [](lua_State* L)
        {
            lua_pushstring(L, "FROM_LUA_REG");
            lua_setglobal(L, "injected");
        });
    BOOST_CHECK_EQUAL(with_reg, "FROM_LUA_REG");

    // load errors and runtime errors surface as RuntimeError
    BOOST_CHECK_THROW(path.ToGCode(GCodeFirmware::Marlin, "!!! not lua !!!"), HsBa::Slicer::RuntimeError);
    BOOST_CHECK_THROW(path.ToGCode(GCodeFirmware::Marlin, "error('script boom')"), HsBa::Slicer::RuntimeError);
}

BOOST_AUTO_TEST_SUITE_END()
