-- my_tdp_export.lua
-- 3DP (TDP, binder jetting) 自定义导出脚本
--
-- 逐层喷射轮廓打包为 zip；喷头/液滴/固化等粘结剂工艺参数由 C++ 侧写入
-- config.configStr（JSON），脚本原样归档即可。
--
-- Lua 环境全局变量:
--   config      : table { path="config.json", configStr="<JSON content>" }
--   images      : array, 每个元素为 { path="layers/N.json", data="<polygon JSON>" }
--   output_path : string, 输出文件路径（由C++传入）
--
-- 返回值: table { success = true/false, export_path = "..." }
-- 注意: 必须返回 table（或 nil），切勿返回字符串，否则会覆盖写出的 zip 文件。

function export_tdp()
    local zipper = Zipper.new()

    zipper:AddByteFile(config.path, config.configStr)

    for i, img in ipairs(images) do
        zipper:AddByteFile(img.path, img.data)
    end

    local readme = "3DP Export Package\n"
    readme = readme .. "==================\n"
    readme = readme .. "Generated by HsBaSlicer 3DP (Binder Jetting) Pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: Head, drop, binder and curing process configuration\n"
    readme = readme .. "  - layers/: Per-layer binder-jet outlines (JSON format)\n"
    zipper:AddByteFile("README.txt", readme)

    local out_path = output_path or "3dp_output.zip"
    zipper:Save(out_path)

    local db_ok, db_err = pcall(function()
        local db = SQLiteAdapter.new()
        db:Connect("3dp_history.db")
        db:Execute([[
            CREATE TABLE IF NOT EXISTS tdp_exports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                output_path TEXT NOT NULL,
                total_layers INTEGER,
                export_time TEXT DEFAULT (datetime('now'))
            )
        ]])
        db:Execute(string.format(
            "INSERT INTO tdp_exports (output_path, total_layers) VALUES ('%s', %d)",
            out_path, #images
        ))
    end)

    if not db_ok then
        print("[3DP Export] Warning: database registration skipped: " .. tostring(db_err))
    end

    return {
        success = true,
        export_path = out_path
    }
end

return export_tdp()
