#include "gcodepath.hpp"

#include <cmath>
#include <format>
#include <fstream>
#include <sstream>

#include <lua.hpp>

#include "base/error.hpp"
#include "utils/LuaNewObject.hpp"

namespace HsBa::Slicer
{

namespace
{
constexpr float kSpeedFactor = 60.0f;  // mm/s -> mm/min
constexpr float kPi = 3.14159265358979323846f;

/// @brief Parse Z height from layer config string (format: "Z:<value>")
float ParseLayerZ(const std::string& config)
{
    if (config.size() > 2 && config[0] == 'Z' && config[1] == ':')
    {
        try
        {
            return std::stof(config.substr(2));
        }
        catch (...)
        {
        }
    }
    return 0.0f;
}

}  // namespace

GCodePath::GCodePath(const GCodePrinterConfig& config,
                     const std::function<void(std::string_view, std::string_view)>& callback)
    : LayersPath(callback), printer_config_(config)
{
}

double GCodePath::CalcExtrusion(double segment_length) const
{
    // Volume of filament extruded = line_width * layer_height * segment_length
    double volume = static_cast<double>(printer_config_.line_width) *
                    static_cast<double>(printer_config_.layer_height) * segment_length;
    // Filament cross-section area
    double radius = static_cast<double>(printer_config_.filament_diameter) / 2.0;
    double area = kPi * radius * radius;
    // E value = volume / area * multiplier
    return (volume / area) * static_cast<double>(printer_config_.extrusion_multiplier);
}

std::string GCodePath::GenerateHeader(GCodeFirmware fw) const
{
    std::ostringstream ss;
    const auto& cfg = printer_config_;

    ss << "; Generated by HsBaSlicer\n";
    ss << "; Firmware: ";
    switch (fw)
    {
    case GCodeFirmware::Marlin:
        ss << "Marlin\n";
        break;
    case GCodeFirmware::RepRap:
        ss << "RepRap/RRF\n";
        break;
    case GCodeFirmware::Klipper:
        ss << "Klipper\n";
        break;
    }
    ss << std::format("; Nozzle: {}mm, Filament: {}mm\n", cfg.nozzle_diameter, cfg.filament_diameter);
    ss << std::format("; Layer height: {}mm\n", cfg.layer_height);
    ss << "\n";

    switch (fw)
    {
    case GCodeFirmware::Marlin:
        ss << "M104 S" << static_cast<int>(cfg.nozzle_temp) << " ; set nozzle temp\n";
        ss << "M140 S" << static_cast<int>(cfg.bed_temp) << " ; set bed temp\n";
        ss << "G28 ; home all axes\n";
        ss << "M109 S" << static_cast<int>(cfg.nozzle_temp) << " ; wait for nozzle temp\n";
        ss << "M190 S" << static_cast<int>(cfg.bed_temp) << " ; wait for bed temp\n";
        ss << "G92 E0 ; reset extruder\n";
        if (cfg.relative_extrusion)
            ss << "M83 ; relative extrusion\n";
        else
            ss << "M82 ; absolute extrusion\n";
        ss << "G1 Z5.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift nozzle\n";
        ss << "\n";
        break;

    case GCodeFirmware::RepRap:
        ss << "M104 S" << static_cast<int>(cfg.nozzle_temp) << " ; set nozzle temp\n";
        ss << "M140 S" << static_cast<int>(cfg.bed_temp) << " ; set bed temp\n";
        ss << "G28 ; home all axes\n";
        ss << "M109 S" << static_cast<int>(cfg.nozzle_temp) << " ; wait for nozzle temp\n";
        ss << "M190 S" << static_cast<int>(cfg.bed_temp) << " ; wait for bed temp\n";
        ss << "G92 E0 ; reset extruder\n";
        if (cfg.relative_extrusion)
            ss << "M83 ; relative extrusion\n";
        else
            ss << "M82 ; absolute extrusion\n";
        ss << "M106 S255 ; fan on full\n";
        ss << "G1 Z5.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift nozzle\n";
        ss << "\n";
        break;

    case GCodeFirmware::Klipper:
        ss << "M104 S" << static_cast<int>(cfg.nozzle_temp) << " ; set nozzle temp\n";
        ss << "M140 S" << static_cast<int>(cfg.bed_temp) << " ; set bed temp\n";
        ss << "G28 ; home all axes\n";
        ss << "M109 S" << static_cast<int>(cfg.nozzle_temp) << " ; wait for nozzle temp\n";
        ss << "M190 S" << static_cast<int>(cfg.bed_temp) << " ; wait for bed temp\n";
        ss << "G92 E0 ; reset extruder\n";
        if (cfg.relative_extrusion)
            ss << "M83 ; relative extrusion\n";
        else
            ss << "M82 ; absolute extrusion\n";
        ss << "SET_PRESSURE_ADVANCE ADVANCE=0.05 ; pressure advance\n";
        ss << "M220 S100 ; set speed factor 100%\n";
        ss << "M221 S100 ; set flow factor 100%\n";
        ss << "SET_FAN_SPEED FAN=part_fan SPEED=1.0 ; fan on full\n";
        ss << "G1 Z5.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift nozzle\n";
        ss << "\n";
        break;
    }

    return ss.str();
}

std::string GCodePath::GenerateFooter(GCodeFirmware fw) const
{
    std::ostringstream ss;
    const auto& cfg = printer_config_;

    ss << "\n; End GCode\n";

    switch (fw)
    {
    case GCodeFirmware::Marlin:
        ss << "M104 S0 ; turn off nozzle heater\n";
        ss << "M140 S0 ; turn off bed heater\n";
        ss << "G91 ; relative positioning\n";
        ss << "G1 E-" << cfg.retract_length << " F" << static_cast<int>(cfg.retract_speed * kSpeedFactor)
           << " ; retract\n";
        ss << "G1 Z10.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift Z\n";
        ss << "G90 ; absolute positioning\n";
        ss << "G28 X Y ; home X Y\n";
        ss << "M84 ; disable motors\n";
        break;

    case GCodeFirmware::RepRap:
        ss << "M104 S0 ; turn off nozzle heater\n";
        ss << "M140 S0 ; turn off bed heater\n";
        ss << "M107 ; fan off\n";
        ss << "G91 ; relative positioning\n";
        ss << "G1 E-" << cfg.retract_length << " F" << static_cast<int>(cfg.retract_speed * kSpeedFactor)
           << " ; retract\n";
        ss << "G1 Z10.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift Z\n";
        ss << "G90 ; absolute positioning\n";
        ss << "G28 X Y ; home X Y\n";
        ss << "M84 ; disable motors\n";
        break;

    case GCodeFirmware::Klipper:
        ss << "M104 S0 ; turn off nozzle heater\n";
        ss << "M140 S0 ; turn off bed heater\n";
        ss << "SET_FAN_SPEED FAN=part_fan SPEED=0.0 ; fan off\n";
        ss << "G91 ; relative positioning\n";
        ss << "G1 E-" << cfg.retract_length << " F" << static_cast<int>(cfg.retract_speed * kSpeedFactor)
           << " ; retract\n";
        ss << "G1 Z10.0 F" << static_cast<int>(cfg.travel_speed * kSpeedFactor) << " ; lift Z\n";
        ss << "G90 ; absolute positioning\n";
        ss << "G28 X Y ; home X Y\n";
        ss << "M84 ; disable motors\n";
        break;
    }

    return ss.str();
}

std::string GCodePath::GenerateLayerGCode(int layer_idx, GCodeFirmware fw) const
{
    if (layer_idx < 0 || layer_idx >= static_cast<int>(layers_.size()))
        return "";

    std::ostringstream ss;
    const auto& layer_data = layers_[layer_idx];
    float z = ParseLayerZ(layer_data.layerConfig);
    const auto& cfg = printer_config_;

    float speed = (layer_idx == 0) ? cfg.first_layer_speed : cfg.print_speed;
    float feed_rate = speed * kSpeedFactor;
    float travel_feed = cfg.travel_speed * kSpeedFactor;

    ss << std::format(";LAYER:{}\n", layer_idx);
    ss << std::format("G0 Z{:.3f} F{:.0f}\n", z, travel_feed);

    double cumulative_e = 0.0;
    bool first_move = true;

    for (const auto& polygon : layer_data.layer)
    {
        if (polygon.empty())
            continue;

        // Travel to start of polygon (with retraction)
        if (cfg.enable_retraction && !first_move)
        {
            ss << std::format("G1 E{:.5f} F{:.0f} ; retract\n",
                              cfg.relative_extrusion ? -cfg.retract_length : cumulative_e - cfg.retract_length,
                              cfg.retract_speed * kSpeedFactor);
        }

        ss << std::format("G0 X{:.3f} Y{:.3f} F{:.0f}\n",
                          polygon.front().x, polygon.front().y, travel_feed);

        if (cfg.enable_retraction && !first_move)
        {
            if (cfg.relative_extrusion)
            {
                ss << std::format("G1 E{:.5f} F{:.0f} ; unretract\n",
                                  cfg.retract_length, cfg.retract_speed * kSpeedFactor);
            }
            else
            {
                ss << std::format("G1 E{:.5f} F{:.0f} ; unretract\n",
                                  cumulative_e, cfg.retract_speed * kSpeedFactor);
            }
        }

        // Print along polygon
        for (size_t i = 1; i <= polygon.size(); ++i)
        {
            const auto& pt = polygon[i % polygon.size()];
            const auto& prev = polygon[(i - 1) % polygon.size()];

            double dx = pt.x - prev.x;
            double dy = pt.y - prev.y;
            double seg_len = std::sqrt(dx * dx + dy * dy);
            double e_value = CalcExtrusion(seg_len);

            if (cfg.relative_extrusion)
            {
                ss << std::format("G1 X{:.3f} Y{:.3f} E{:.5f} F{:.0f}\n",
                                  pt.x, pt.y, e_value, feed_rate);
            }
            else
            {
                cumulative_e += e_value;
                ss << std::format("G1 X{:.3f} Y{:.3f} E{:.5f} F{:.0f}\n",
                                  pt.x, pt.y, cumulative_e, feed_rate);
            }
        }

        first_move = false;
    }

    return ss.str();
}

std::string GCodePath::ToGCode(GCodeFirmware firmware) const
{
    std::ostringstream ss;
    ss << GenerateHeader(firmware);

    for (int i = 0; i < static_cast<int>(layers_.size()); ++i)
    {
        ss << GenerateLayerGCode(i, firmware);
    }

    ss << GenerateFooter(firmware);
    return ss.str();
}

void GCodePath::SaveGCode(const std::filesystem::path& path, GCodeFirmware firmware) const
{
    auto gcode = ToGCode(firmware);
    std::ofstream ofs(path, std::ios::binary);
    if (!ofs)
    {
        throw RuntimeError("Failed to open output file: " + path.string());
    }
    ofs << gcode;
}

std::string GCodePath::ToGCode(GCodeFirmware firmware, std::string_view script,
                               const std::function<void(lua_State*)>& lua_reg) const
{
    if (script.empty())
        return ToGCode(firmware);

    // Generate base GCode
    std::string base_gcode = ToGCode(firmware);

    // Run Lua post-processing
    auto L = MakeUniqueLuaState();
    if (!L)
        throw RuntimeError("Lua init failed");
    luaL_openlibs(L.get());
    if (lua_reg)
        lua_reg(L.get());

    // Push GCode as global
    lua_pushlstring(L.get(), base_gcode.c_str(), base_gcode.size());
    lua_setglobal(L.get(), "gcode");

    // Push firmware name
    const char* fw_name = "marlin";
    if (firmware == GCodeFirmware::RepRap)
        fw_name = "reprap";
    else if (firmware == GCodeFirmware::Klipper)
        fw_name = "klipper";
    lua_pushstring(L.get(), fw_name);
    lua_setglobal(L.get(), "firmware");

    // Push printer config as table
    lua_newtable(L.get());
    lua_pushnumber(L.get(), printer_config_.nozzle_temp);
    lua_setfield(L.get(), -2, "nozzle_temp");
    lua_pushnumber(L.get(), printer_config_.bed_temp);
    lua_setfield(L.get(), -2, "bed_temp");
    lua_pushnumber(L.get(), printer_config_.print_speed);
    lua_setfield(L.get(), -2, "print_speed");
    lua_pushnumber(L.get(), printer_config_.travel_speed);
    lua_setfield(L.get(), -2, "travel_speed");
    lua_pushnumber(L.get(), printer_config_.layer_height);
    lua_setfield(L.get(), -2, "layer_height");
    lua_pushnumber(L.get(), printer_config_.line_width);
    lua_setfield(L.get(), -2, "line_width");
    lua_pushinteger(L.get(), static_cast<int>(layers_.size()));
    lua_setfield(L.get(), -2, "total_layers");
    lua_setglobal(L.get(), "printer_config");

    int loadStatus = luaL_loadbuffer(L.get(), script.data(), script.size(), "GCodePostProcess");
    if (loadStatus != LUA_OK)
    {
        std::string err = lua_tostring(L.get(), -1);
        throw RuntimeError(std::format("-- Lua load error: {}", err));
    }

    int callStatus = lua_pcall(L.get(), 0, LUA_MULTRET, 0);
    if (callStatus != LUA_OK)
    {
        std::string err = lua_tostring(L.get(), -1);
        throw RuntimeError(std::format("-- Lua runtime error: {}", err));
    }

    // If Lua returned a string, use it as the final GCode
    int nret = lua_gettop(L.get());
    if (nret > 0 && lua_isstring(L.get(), -1))
    {
        size_t len = 0;
        const char* s = lua_tolstring(L.get(), -1, &len);
        return std::string(s, len);
    }

    // Otherwise try global 'result'
    lua_getglobal(L.get(), "result");
    if (lua_isstring(L.get(), -1))
    {
        size_t len = 0;
        const char* s = lua_tolstring(L.get(), -1, &len);
        return std::string(s, len);
    }

    // Fallback to base GCode
    return base_gcode;
}

}  // namespace HsBa::Slicer
