-- my_sls_export.lua
-- Custom 流水线中 saveSlsPackage 调用的 SLS 导出脚本
--
-- 由 my_sls_pipeline.lua 通过 HsBa.saveSlsPackage{..., script="scripts/my_sls_export.lua"}
-- 触发。C++ 侧已把每层轮廓序列化为 JSON，本脚本决定最终打包格式并注册数据库，
-- 体现“SLS 无标准输出格式、导出行为完全由 Lua 控制”的约定。
--
-- Lua 环境全局变量（由 C++ 注入）:
--   config      : table { path="config.json", configStr="<JSON content>" }
--   images      : array, 每个元素为 { path="layers/N.json", data="<polygon JSON>" }
--   output_path : string, 输出 zip 路径
--
-- 可用的已注册 Lua 库（方法名与 C++ 绑定一致，均为 PascalCase）:
--   Zipper        : AddByteFile(name, data) / AddFile(name, path) / Save(path)
--   Cipher        : 加密 / 哈希
--   SQLiteAdapter : new() 后调用 Connect / Execute / Query ...
--
-- 重要: 本脚本的返回值若是字符串，C++ 会用它覆盖写入 output_path（破坏 zip），
--       因此这里只返回 table，真正的压缩包由 Zipper:Save 写出。

function export_sls()
    -- 1. 创建 zip 压缩包
    local zipper = Zipper.new()

    -- 2. 写入配置文件
    zipper:AddByteFile(config.path, config.configStr)

    -- 3. 写入每层的多边形轮廓数据
    for _, img in ipairs(images) do
        zipper:AddByteFile(img.path, img.data)
    end

    -- 4. 写入 README 说明
    local readme = "SLS Export Package (Custom Lua pipeline)\n"
    readme = readme .. "===================================\n"
    readme = readme .. "Generated by the HsBaSlicer Custom Lua SLS pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: slicing and laser parameters\n"
    readme = readme .. "  - layers/: per-layer polygon outlines (JSON format)\n\n"
    readme = readme .. 'Layer JSON format:\n  { "layer": N, "z_height": Z, "outlines": { "polygons": [...] } }\n'
    zipper:AddByteFile("README.txt", readme)

    -- 5. 保存 zip 文件
    local out_path = output_path or "sls_output.zip"
    zipper:Save(out_path)

    -- 6. 注册数据库记录（可选，失败不影响导出结果）
    local db_ok, db_err = pcall(function()
        local db = SQLiteAdapter.new()
        db:Connect("sls_history.db")
        db:Execute([[
            CREATE TABLE IF NOT EXISTS sls_exports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                output_path TEXT NOT NULL,
                total_layers INTEGER,
                export_time TEXT DEFAULT (datetime('now'))
            )
        ]])
        db:Execute(string.format(
            "INSERT INTO sls_exports (output_path, total_layers) VALUES ('%s', %d)",
            out_path, #images))
    end)

    if not db_ok then
        print("[SLS Export] Warning: database registration skipped: " .. tostring(db_err))
    end

    return {
        success = true,
        export_path = out_path
    }
end

-- 执行导出（返回 table，避免覆盖 zip 文件）
return export_sls()
