-- my_waam_path.lua
-- WAAM 自定义机器人代码生成脚本（可选）
--
-- 当在配置中设置 path_lua_script 时，WAAM 流水线会用本脚本代替内置的
-- ABB/KUKA/FANUC 代码生成器，输出用户自定义的机器人程序文本。
--
-- Lua 环境全局变量:
--   header            : string, 头部说明
--   startProgramFunc  : string, 起始程序名（可能为空）
--   endProgramFunc    : string, 结束程序名（可能为空）
--   points            : array, 每个元素为
--                       { end={x,y,z}, middle={x,y,z}, velocity=number, type=string }
--
-- 返回值: string —— 完整的机器人程序文本（会被写入输出文件）。
-- 与导出型脚本（zip）不同：机器人路径脚本必须返回字符串。

function export_waam()
    local buf = {}
    buf[#buf + 1] = "-- Custom WAAM robot program (generated by my_waam_path.lua)\n"

    if startProgramFunc and startProgramFunc ~= "" then
        buf[#buf + 1] = string.format("PROGRAM %s\n", startProgramFunc)
    end

    for i, pt in ipairs(points) do
        local pos = pt["end"]
        local x = pos.x
        local y = pos.y
        local z = pos.z
        local v = pt.velocity or 100
        if pt.type == "MoveJ" then
            buf[#buf + 1] = string.format("MOVEJ X=%.3f Y=%.3f Z=%.3f V=%.1f\n", x, y, z, v)
        else
            buf[#buf + 1] = string.format("MOVEL X=%.3f Y=%.3f Z=%.3f V=%.1f [WELD ON]\n", x, y, z, v)
        end
    end

    if endProgramFunc and endProgramFunc ~= "" then
        buf[#buf + 1] = string.format("ENDPROGRAM %s\n", endProgramFunc)
    end

    return table.concat(buf)
end

return export_waam()
