-- my_sla_export.lua
-- 自定义SLA导出脚本
--
-- 该脚本演示如何自定义导出格式。默认导出为zip包（config.json + 层轮廓SVG）。
-- 用户可以在此脚本中实现自定义导出逻辑，例如：
--   - 修改配置文件格式（XML、INI等）
--   - 添加额外的元数据
--   - 自定义图片格式或命名规则
--
-- Lua 环境全局变量:
--   layer_outlines : 所有层的轮廓数据 { layer1 = {...}, layer2 = {...}, ... }
--   floor_data     : 地板数据
--   support_data   : 支撑数据 { layer1 = {...}, layer2 = {...}, ... }
--   config         : 流水线配置表（同sla_pipeline配置）
--   total_layers   : 总层数
--   output_path    : 输出路径
--
-- 可用函数:
--   export.write_json(filename, content)  -- 写入JSON文件到zip包
--   export.write_svg(filename, polygons)  -- 写入SVG文件到zip包
--   export.add_file(filename, content)    -- 添加任意文件到zip包
--   export.save_zip(path)                 -- 保存zip包到指定路径
--
-- 返回值: 导出结果表 { success = true/false, export_path = "..." }

function export_sla()
    -- 1. 生成配置文件（此处使用JSON格式）
    local config_content = "{\n"
    config_content = config_content .. '  "layer_height": ' .. config.layer_height .. ',\n'
    config_content = config_content .. '  "first_layer_height": ' .. config.first_layer_height .. ',\n'
    config_content = config_content .. '  "total_layers": ' .. total_layers .. ',\n'
    config_content = config_content .. '  "bottom_exposure_time": ' .. config.bottom_exposure_time .. ',\n'
    config_content = config_content .. '  "normal_exposure_time": ' .. config.normal_exposure_time .. ',\n'
    config_content = config_content .. '  "lift_distance": ' .. config.lift_distance .. ',\n'
    config_content = config_content .. '  "lift_speed": ' .. config.lift_speed .. ',\n'
    config_content = config_content .. '  "retract_speed": ' .. config.retract_speed .. ',\n'
    config_content = config_content .. '  "model_name": "' .. (config.model_name or "unknown") .. '"\n'
    config_content = config_content .. "}\n"

    export.write_json("config.json", config_content)

    -- 2. 添加README文件说明导出内容
    local readme = "SLA Export Package\n"
    readme = readme .. "================\n"
    readme = readme .. "Generated by HsBaSlicer SLA Pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: Print configuration\n"
    readme = readme .. "  - layers/: Layer contour SVG images\n"
    readme = readme .. "  - floor/: Floor/raft SVG images\n"
    readme = readme .. "  - supports/: Support SVG images (if enabled)\n"
    export.add_file("README.txt", readme)

    -- 3. 导出层轮廓（默认每层一个SVG）
    for i = 0, total_layers - 1 do
        local filename = string.format("layers/layer_%04d.svg", i)
        export.write_svg(filename, layer_outlines[i + 1])  -- Lua 1-based
    end

    -- 4. 导出地板
    if floor_data and #floor_data > 0 then
        export.write_svg("floor/floor_raft.svg", floor_data)
    end

    -- 5. 导出支撑（如果有）
    if support_data then
        for i = 0, total_layers - 1 do
            local layer_support = support_data[i + 1]  -- Lua 1-based
            if layer_support and #layer_support > 0 then
                local filename = string.format("supports/layer_%04d.svg", i)
                export.write_svg(filename, layer_support)
            end
        end
    end

    -- 6. 保存zip包
    export.save_zip(output_path or "sla_output.zip")

    return {
        success = true,
        export_path = output_path or "sla_output.zip"
    }
end

return export_sla()
