-- my_lom_export.lua
-- LOM (Laminated Object Manufacturing) 自定义导出脚本
--
-- 每层对应一张板材轮廓；切割/粘合参数由 C++ 侧写入 config.configStr（JSON）。
-- 该脚本将逐层轮廓与配置打包为 zip 并登记数据库。
--
-- 返回值: table { success = true/false, export_path = "..." }
-- 注意: 必须返回 table（或 nil），切勿返回字符串，否则会覆盖写出的 zip 文件。

function export_lom()
    local zipper = Zipper.new()

    zipper:AddByteFile(config.path, config.configStr)

    for i, img in ipairs(images) do
        zipper:AddByteFile(img.path, img.data)
    end

    local readme = "LOM Export Package\n"
    readme = readme .. "==================\n"
    readme = readme .. "Generated by HsBaSlicer LOM Pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: Sheet, cut and bond process configuration\n"
    readme = readme .. "  - layers/: Per-sheet contour outlines (JSON format)\n"
    zipper:AddByteFile("README.txt", readme)

    local out_path = output_path or "lom_output.zip"
    zipper:Save(out_path)

    local db_ok, db_err = pcall(function()
        local db = SQLiteAdapter.new()
        db:Connect("lom_history.db")
        db:Execute([[
            CREATE TABLE IF NOT EXISTS lom_exports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                output_path TEXT NOT NULL,
                total_layers INTEGER,
                export_time TEXT DEFAULT (datetime('now'))
            )
        ]])
        db:Execute(string.format(
            "INSERT INTO lom_exports (output_path, total_layers) VALUES ('%s', %d)",
            out_path, #images
        ))
    end)

    if not db_ok then
        print("[LOM Export] Warning: database registration skipped: " .. tostring(db_err))
    end

    return {
        success = true,
        export_path = out_path
    }
end

return export_lom()
