-- my_slm_export.lua
-- SLM (Selective Laser Melting) 自定义导出脚本
--
-- SLM 复用 SLS 式的 zip + 数据库打包流程；金属工艺参数（材料/光源/保护气）
-- 由 C++ 侧写入 config.configStr（JSON），脚本原样归档即可。
--
-- Lua 环境全局变量:
--   config      : table { path="config.json", configStr="<JSON content>" }
--   images      : array, 每个元素为 { path="layers/N.json", data="<polygon JSON>" }
--   output_path : string, 输出文件路径（由C++传入）
--
-- 返回值: table { success = true/false, export_path = "..." }
-- 注意: 必须返回 table（或 nil），切勿返回字符串，否则会覆盖写出的 zip 文件。

function export_slm()
    local zipper = Zipper.new()

    zipper:AddByteFile(config.path, config.configStr)

    for i, img in ipairs(images) do
        zipper:AddByteFile(img.path, img.data)
    end

    local readme = "SLM Export Package\n"
    readme = readme .. "==================\n"
    readme = readme .. "Generated by HsBaSlicer SLM Pipeline\n\n"
    readme = readme .. "Contents:\n"
    readme = readme .. "  - config.json: Slicing, laser and metal process configuration\n"
    readme = readme .. "  - layers/: Per-layer polygon outlines (JSON format)\n"
    zipper:AddByteFile("README.txt", readme)

    local out_path = output_path or "slm_output.zip"
    zipper:Save(out_path)

    local db_ok, db_err = pcall(function()
        local db = SQLiteAdapter.new()
        db:Connect("slm_history.db")
        db:Execute([[
            CREATE TABLE IF NOT EXISTS slm_exports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                output_path TEXT NOT NULL,
                total_layers INTEGER,
                export_time TEXT DEFAULT (datetime('now'))
            )
        ]])
        db:Execute(string.format(
            "INSERT INTO slm_exports (output_path, total_layers) VALUES ('%s', %d)",
            out_path, #images
        ))
    end)

    if not db_ok then
        print("[SLM Export] Warning: database registration skipped: " .. tostring(db_err))
    end

    return {
        success = true,
        export_path = out_path
    }
end

return export_slm()
