name: Build on macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        shell: bash
        run: |
          brew update
          brew install cmake ninja python autoconf automake libtool autoconf-archive

      - name: Clone vcpkg and bootstrap
        shell: bash
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
            ./vcpkg/vcpkg integrate install
          fi
          echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV

      - name: Set up vcpkg binary cache backend
        shell: bash
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

      - name: Cache vcpkg downloads cache
        uses: actions/cache@v5
        with:
          path: ${VCPKG_ROOT}/downloads
          key: vcpkg-macos-${{ hashFiles('vcpkg.json') }}

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build -S . -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release

      - name: Run tests
        shell: bash
        run: |
          cd build/tests
          ctest --build-config Release --output-on-failure --parallel 2
        continue-on-error: true
